config/routes.rb
Rails.application.routes.draw do
  resources :patient_forms
  root to: "patient_forms#show"
  devise_for :admins
  devise_for :patients
  
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"
  
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admins_on_email                 (email) UNIQUE
#  index_admins_on_reset_password_token  (reset_password_token) UNIQUE
#
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :patient_forms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_patients_on_email                 (email) UNIQUE
#  index_patients_on_reset_password_token  (reset_password_token) UNIQUE
#
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :patient_forms
end

app/models/patient_form.rb
# == Schema Information
#
# Table name: patient_forms
#
#  id         :integer          not null, primary key
#  body       :text
#  image      :string
#  severity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  admin_id   :integer          not null
#  patient_id :integer          not null
#
# Indexes
#
#  index_patient_forms_on_admin_id    (admin_id)
#  index_patient_forms_on_patient_id  (patient_id)
#
# Foreign Keys
#
#  admin_id    (admin_id => admins.id)
#  patient_id  (patient_id => patients.id)
#
class PatientForm < ApplicationRecord
  belongs_to :patient
  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_patient!
end

app/controllers/patient_forms_controller.rb
class PatientFormsController < ApplicationController
  before_action :set_patient_form, only: %i[ show edit update destroy ]

  # GET /patient_forms or /patient_forms.json
  def index
    @patient_forms = PatientForm.all
  end

  # GET /patient_forms/1 or /patient_forms/1.json
  def show
  end

  # GET /patient_forms/new
  def new
    @patient_form = PatientForm.new
  end

  # GET /patient_forms/1/edit
  def edit
  end

  # POST /patient_forms or /patient_forms.json
  def create
    @patient_form = PatientForm.new(patient_form_params)

    respond_to do |format|
      if @patient_form.save
        format.html { redirect_to patient_form_url(@patient_form), notice: "Patient form was successfully created." }
        format.json { render :show, status: :created, location: @patient_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_forms/1 or /patient_forms/1.json
  def update
    respond_to do |format|
      if @patient_form.update(patient_form_params)
        format.html { redirect_to patient_form_url(@patient_form), notice: "Patient form was successfully updated." }
        format.json { render :show, status: :ok, location: @patient_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_forms/1 or /patient_forms/1.json
  def destroy
    @patient_form.destroy!

    respond_to do |format|
      format.html { redirect_to patient_forms_url, notice: "Patient form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_form
      @patient_form = PatientForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_form_params
      params.require(:patient_form).permit(:image, :body, :severity, :patient_id, :admin_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render partial: "shared/cdn_links"%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <%= render partial: "shared/notifications"%>
    <%= yield %>
  </body>
</html>

app/views/patient_forms/_form.html.erb
<%= form_with(model: patient_form) do |form| %>
  <% if patient_form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient_form.errors.count, "error") %> prohibited this patient_form from being saved:</h2>

      <ul>
        <% patient_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :severity, style: "display: block" %>
    <%= form.number_field :severity %>
  </div>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :admin_id, style: "display: block" %>
    <%= form.text_field :admin_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patient_forms/_patient_form.html.erb
<div id="<%= dom_id patient_form %>">
  <p>
    <strong>Image:</strong>
    <%= patient_form.image %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= patient_form.body %>
  </p>

  <p>
    <strong>Severity:</strong>
    <%= patient_form.severity %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= patient_form.patient_id %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= patient_form.admin_id %>
  </p>

</div>

app/views/patient_forms/edit.html.erb
<h1>Editing patient form</h1>

<%= render "form", patient_form: @patient_form %>

<br>

<div>
  <%= link_to "Show this patient form", @patient_form %> |
  <%= link_to "Back to patient forms", patient_forms_path %>
</div>

app/views/patient_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patient forms</h1>

<div id="patient_forms">
  <% @patient_forms.each do |patient_form| %>
    <%= render patient_form %>
    <p>
      <%= link_to "Show this patient form", patient_form %>
    </p>
  <% end %>
</div>

<%= link_to "New patient form", new_patient_form_path %>

app/views/patient_forms/new.html.erb
<h1>New patient form</h1>

<%= render "form", patient_form: @patient_form %>

<br>

<div>
  <%= link_to "Back to patient forms", patient_forms_path %>
</div>

app/views/patient_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient_form %>

<div>
  <%= link_to "Edit this patient form", edit_patient_form_path(@patient_form) %> |
  <%= link_to "Back to patient forms", patient_forms_path %>

  <%= button_to "Destroy this patient form", @patient_form, method: :delete %>
</div>

app/views/shared/_cdn_links.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">ERFlow</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Patient Form", new_patient_form_path(current_user), class: "nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Queue</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if !patient_signed_in? %>
        <li class="nav-item">
          <%=link_to "Sign In", patient_session_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "Sign up", new_patient_registration_path, class: "nav-link"%>
        </li>
      <%else%>
        <li class="nav-item">
          <%=link_to "Sign Out", destroy_patient_session_path, data: { turbo_method: :delete }, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "Update Profile", edit_patient_registration_path, class: "nav-link"%>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>